[Service]
Environment="CAPABILITY_REUSE_MODE=active"
Environment="CAPABILITY_REUSE_ACTIVE_CAPABILITIES=hmp-healthcheck"
Environment="CAPABILITY_REUSE_PERMISSIONS=hmp.network.read"
Environment="CAPABILITY_REUSE_AVAILABLE_CAPABILITIES=hmp_client_installed"
Environment="CAPABILITY_REUSE_COLLECTOR_PEER_ID=peer70"
